# docker-compose.yml

version: '3.9'
services:

  postgres:
    image: postgres: latest
    restart: always
    environment:
      - POSTGRES_USER=my-postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: